version: '3'
services:

 pgsql:
   image: postgresql:9.5
   environment:
       PGSQL_DB_1_NAME: 'musichub'

 backend:
   labels:
       org.label-schema.name: 'backend'
   build:
     context: ./back
   ports:
        - "8000:8000"
   links:
     - pgsql
   volumes:
     - "/static"
   restart: always

